services:

  mysql-db:
    image: mysql:8.0
    container_name: project10-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project10
    ports:
      - "3308:3306"   # change to 3308:3306 if host MySQL already running
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project10-network

  project10-backend:
    build: .               # <- Dockerfile se local build
    image: project10-backend:latest  # <- local image name
    container_name: project10-backend
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/project10?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - project10-network

networks:
  project10-network:
    driver: bridge

volumes:
  mysql_data:
